### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by DCRichards** [drone-plugins/drone-volume-cache#3]
Nobody currently knows how to use this...

**Comment by krisleech** [comment]
My first attempt:

```
pipeline:
  restore-cache:
    image: plugins/volume-cache
    restore: true
    mount:
      - ./bundle_cache
    volumes:
      - /tmp/cache:/cache
```

but I get an error `Cache could not be restored open /cache/Propheris/oxygen/.tar: no such file or directory`.

**Comment by bugbuilder** [comment]
@krisleech at this moment the filepath has a bad reference to the repo branch name, to avoid this you need to add the file option to the pluging

```
pipeline:
  restore-cache:
    image: plugins/volume-cache
    file: cache.tar
    restore: true
    mount:
      - ./bundle_cache
    volumes:
      - /tmp/cache:/cache
      
  test:
    image: do/something
    commands:
      - mkdir -p ./bundle_cache
      - touch ./bundle_cache/test
      - touch ./bundle_cache/test2

      
  rebuild-cache:
    image: plugins/volume-cache
    file: cache.tar
    rebuild: true
    mount:
      - ./bundle_cache
    volumes:
      - /tmp/cache:/cache      
```
