### ISSUE TITLE
Submit documentation to plugins.drone.io

### ISSUE THREAD

**Issue by tboerger** [drone-plugins/drone-volume-cache#8]

**Comment by Timshel** [comment]
Hi, I would be interested in using this plugin but I can't find any information on its usage.

**Comment by mvdan** [comment]
For everyone's sake, here's what we're currently using. It uses the repo name as the filename, so all branches within a repo share the same cache. And the caches are stored in the `/tmp/cache` directory of the host.

```
pipeline:
  restore-cache:
    image: plugins/volume-cache
    restore: true
    file: ${DRONE_REPO_NAME}.tar
    mount:
      - ./list-of-dirs-to-cache
    volumes:
      - /tmp/cache:/cache

[your build steps]

  rebuild-cache:
    image: plugins/volume-cache
    rebuild: true
    file: ${DRONE_REPO_NAME}.tar
    mount:
      - ./list-of-dirs-to-cache
    volumes:
      - /tmp/cache:/cache
```

I don't know if it's the right setup, but it seems to work okay.
